use_frameworks!

target 'SwiftPopup_Example' do
  pod 'SwiftPopup', :path => '../'

  target 'SwiftPopup_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
